### PR TITLE
CMake4git integration

### PR DESCRIPTION
**Pull request by forGGe**
Original repo https://github.com/Oleh-Kravchenko/cmake-version4git
@Oleh-Kravchenko looking forward for your comments :)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 07989fe593c988d34b6bec37c634ca1122a44f3f
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/forGGe/theCore

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 07989fe593c988d34b6bec37c634ca1122a44f3f
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/forGGe/theCore

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 07989fe593c988d34b6bec37c634ca1122a44f3f
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/forGGe/theCore

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 07989fe593c988d34b6bec37c634ca1122a44f3f
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/forGGe/theCore

---
This message was auto-generated by https://gitcop.com

**Comment by rasendubi** [comment]
@forGGe @Oleh-Kravchenko would that work if someone copies theCore as a plain directory (i.e., without a git repo)? For example, that could be done using GitHub ability to serve `.tar.gz` of projects (which are faster to download than to clone a git repo, and is a default method in Nixpkgs)

Also, can I build the project if I don't have git installed? (again, getting sources as a `.tar.gz` archive)

**Comment by forGGe** [comment]
> @forGGe @Oleh-Kravchenko would that work if someone copies theCore as a plain directory (i.e., without a git repo)? For example, that could be done using GitHub ability to serve .tar.gz of projects (which are faster to download than to clone a git repo, and is a default method in Nixpkgs)

Sure you will be able to build it. Version string is empty when cmake4git is missing: 

https://github.com/forGGe/theCore/blob/04843a885544df48607b17eb8fbe2ed7ab405b12/lib/utils/version.in.cpp#L20-L26

Will it be better to put last version there instead?

> Also, can I build the project if I don't have git installed? (again, getting sources as a .tar.gz archive)

It will likely fail: https://github.com/Oleh-Kravchenko/cmake-version4git/blob/master/cmake/cmake-version4git.cmake#L1

Good catch, thanks!

**Comment by rasendubi** [comment]
Yes, setting the last version in the repo itself is the Right Thing©

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 07989fe593c988d34b6bec37c634ca1122a44f3f
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/forGGe/theCore

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
