### PR TITLE
#238 Colorize cmake output

### PR DESCRIPTION
**Pull request by Dubland**
/cc @forGGe

### CODE REVIEW

**Comment by forGGe** [comment]
@Dubland thanks! Branch has some conflicts, could you please resolve it?

**Comment by Dubland** [comment]
conflict in lib/cpp/CMakeLists.txt

<<<<<<< colorized_output
    msg_info("Console is enabled.")
=======
    message(STATUS "Console is enabled.")
>>>>>>> develop

don't know how I must resolve it

**Comment by forGGe** [comment]
Are you sure that you resolve it? Rebase onto upstream develop and try again.

**Comment by Dubland** [comment]
Fixed.

**Review by forGGe — APPROVED** [review]
Looks good.

**Comment by forGGe** [comment]
Locally tested - few things is missing. Please check Dubland#1

**Comment by Dubland** [comment]
Check it now.
For tests need include build_api.cmake if we wanna use colorized output. Shall I do it?

**Comment by forGGe** [comment]
Thanks!

**Pull request merged**
