### PR TITLE
Relicense to MPL

### PR DESCRIPTION
**Pull request by forGGe**
The project comes under the LGPL3.0+. It could be worthwhile to re-license under MPLv2, since it has the SLE (Static Linking Exception) baked in and is a standard license.

It is largely motivated by the embedded industry where the  static linkage is a common practice.

So, let's do it right.

This is the list of contributors according to `git shortlog --summary --numbered`:

- [x] @vadimol 
- [x] @Dubland 
- [x] @rasendubi 
- [x] @velichechka 
- [x] @GamovCoder 
- [x] @InnusiG 
- [x] @RostakaGmfun 

Could you kindly reply "I hereby agree to publish my contributions to theCore under the MPLv2 license"?

If you have any objection to relicensing your contributions, explain your reasons.

P.S. This request is inspired by dftlibs/xcfun#17 . Happy re-licensing for them!

### CODE REVIEW

**Comment by forGGe** [comment]
Also, check MPL FAQ here: https://www.mozilla.org/en-US/MPL/2.0/FAQ/

**Comment by InnusiG** [comment]
I hereby agree to publish my contributions to theCore under the MPLv2
license. ✌

**Comment by rasendubi** [comment]
How about GPL + explicit static linking exception? (like freeRTOS do)

**Comment by vadimol** [comment]
I hereby agree to publish my contributions to theCore under the MPLv2 license.

**Comment by forGGe** [comment]
@rasendubi 
In ZeroMQ words:
> MPLv2 offers largely the same advantages as our custom LGPLv3 + static link exception license, with the added advantage of being a standard license, thus easier for corporate lawyers to accept.

Just a convenient shortcut. Probably I'll post more arguments here.

**Comment by Dubland** [comment]
I hereby agree to publish my contributions to theCore under the MPLv2 license.

**Comment by RostakaGmfun** [comment]
I hereby agree to publish my contributions to theCore under the MPLv2 license

**Comment by rasendubi** [comment]
I hereby agree to publish my contributions to theCore under the MPLv2 license

**Comment by GamovCoder** [comment]
I hereby agree to publish my contributions to theCore under the MPLv2 license

**Comment by velichechka** [comment]
I hereby agree to publish my contributions to theCore under the MPLv2 license.

**Comment by forGGe** [comment]
Thanks to everyone, folks! I'm merging this right now :)

**Pull request merged**
